name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: continuous_integration
    runs-on: ubuntu-latest
    environment: WORKFLOW
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    
      - name: Build Docker image
        run: docker build -t ${{ vars.IMAGE_NAME }} .
      
      - name: Push Docker image to Docker Hub
        run: docker push ${{ vars.IMAGE_NAME }}

  deploy:
    name: continuous_deployment
    runs-on: self-hosted
    needs: build
    environment: WORKFLOW
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Stop existing container
        run: docker stop ${{ vars.CONTAINER_NAME }} || true

      - name: Remove existing container
        run: docker rm -f ${{ vars.CONTAINER_NAME }} || true

      - name: Remove existing image
        run: docker rmi ${{ vars.IMAGE_NAME }} || true

      - name: Pull Docker image
        run: docker pull ${{ vars.IMAGE_NAME }}

      - name: Deploy to EC2
        run: docker run -d -p 80:80 --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME }}
